name: matrix-synapse-bridged # you probably want to 'snapcraft register <name>'
base: core22
version: '1.91'
summary: Synapse is an open-source Matrix server written by the Matrix.org Foundation.
description: |
  Briefly, Matrix is an open standard for communications on the internet,
  supporting federation, encryption and VoIP. Matrix.org has more to
  say about the goals of the Matrix project, and the formal specification
  describes the technical details.

  For setup instructions see: https://github.com/danbishop/matrix-synapse-bridged

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

website: https://github.com/danbishop/matrix-synapse-bridged
contact: d@nbishop.uk
license: GPL-3.0

package-repositories:
  - type: apt
    components: [main]
    suites: [jammy]
    key-id: AAF9AE843A7584B5A3E4CD2BCF45A512DE2DA058
    url: https://packages.matrix.org/debian/

parts:
  synapse:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
    stage-packages:
      - matrix-synapse-py3
      - libpq5
  default-config:
      # custom default config is shipped for the snap version
      plugin: dump
      source: snap/local/default
      organize:
        '*': default/
# Make /var/lib/synapse inside the snap point to $SNAP_DATA directory as you
# can't use the $SNAP_DATA variable in synapse's yaml files
layout:
    /var/lib/matrix-synapse:
      bind: $SNAP_DATA
apps:
  synapse:
    command: synapse.sh
    daemon: simple
    plugs: [network, network-bind]
  register-new-matrix-user:
    command: opt/venvs/matrix-synapse/bin/python $SNAP/opt/venvs/matrix-synapse/bin/register_new_matrix_user -c $SNAP_DATA/homeserver.yaml
    plugs: [network, network-bind]
